// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// ExpandResponse defines model for ExpandResponse.
type ExpandResponse struct {
	OriginalUrl string `json:"original_url"`
}

// ShortenRequest defines model for ShortenRequest.
type ShortenRequest struct {
	Url string `json:"url"`
}

// ShortenResponse defines model for ShortenResponse.
type ShortenResponse struct {
	ShortUrl string `json:"short_url"`
}

// PostShortenJSONRequestBody defines body for PostShorten for application/json ContentType.
type PostShortenJSONRequestBody = ShortenRequest
