// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/samantonio28/meowcut/internal/domain"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// FindByOriginalURL mocks base method.
func (m *MockLinkRepository) FindByOriginalURL(originalURL string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOriginalURL", originalURL)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOriginalURL indicates an expected call of FindByOriginalURL.
func (mr *MockLinkRepositoryMockRecorder) FindByOriginalURL(originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOriginalURL", reflect.TypeOf((*MockLinkRepository)(nil).FindByOriginalURL), originalURL)
}

// FindByShortID mocks base method.
func (m *MockLinkRepository) FindByShortID(shortID string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortID", shortID)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortID indicates an expected call of FindByShortID.
func (mr *MockLinkRepositoryMockRecorder) FindByShortID(shortID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortID", reflect.TypeOf((*MockLinkRepository)(nil).FindByShortID), shortID)
}

// Save mocks base method.
func (m *MockLinkRepository) Save(link domain.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLinkRepositoryMockRecorder) Save(link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLinkRepository)(nil).Save), link)
}
