// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/cutter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLinkCutter is a mock of LinkCutter interface.
type MockLinkCutter struct {
	ctrl     *gomock.Controller
	recorder *MockLinkCutterMockRecorder
}

// MockLinkCutterMockRecorder is the mock recorder for MockLinkCutter.
type MockLinkCutterMockRecorder struct {
	mock *MockLinkCutter
}

// NewMockLinkCutter creates a new mock instance.
func NewMockLinkCutter(ctrl *gomock.Controller) *MockLinkCutter {
	mock := &MockLinkCutter{ctrl: ctrl}
	mock.recorder = &MockLinkCutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkCutter) EXPECT() *MockLinkCutterMockRecorder {
	return m.recorder
}

// Cut mocks base method.
func (m *MockLinkCutter) Cut(originalURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cut", originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cut indicates an expected call of Cut.
func (mr *MockLinkCutterMockRecorder) Cut(originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cut", reflect.TypeOf((*MockLinkCutter)(nil).Cut), originalURL)
}
